language: java
install: true
script: mvn verify javadoc:javadoc coveralls:report -Pcoverage
jdk:
  - openjdk11
branches:
  only:
     - master
     - /\d\.0\.0-RC/
cache:
  directories:
    - '$HOME/.m2/repository'
dist: trusty

